# Generated by Django 5.1.1 on 2024-09-29 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mahsulot nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stock/')),
                ('description', models.TextField(blank=True, null=True)),
                ('time_limit', models.DurationField(blank=True, null=True, verbose_name='Aktiv vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Aktsiya yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Aktsiyalar',
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Telefon raqam')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='F.I.Sh')),
                ('location', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Manzil')),
                ('joined_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name="Foydalanuvchi qo'shilgan vaqt")),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="Foydalanuvchi ma'lumotlari o'zgartirilgan vaqt")),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.TextField(blank=True, null=True, verbose_name="Mahsulotlar ro'yxati")),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Buyurtma berilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="Buyurtma o'zgartirilgan vaqt")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.users', verbose_name='Buyurtmqa egasi')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Buyurtmalar',
                'db_table': 'order',
            },
        ),
    ]
