# Generated by Django 5.1.1 on 2024-09-29 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 29, 15, 54, 36, 699241), null=True, verbose_name='Buyurtma berilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 29, 15, 54, 36, 699241), null=True, verbose_name='Aktsiya yaratilgan vaqt'),
        ),
    ]
