# Generated by Django 5.1.1 on 2024-09-29 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_order_created_at_alter_stock_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='image_id',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Rasm kodi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 29, 16, 2, 38, 430), null=True, verbose_name='Buyurtma berilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 29, 16, 2, 38, 430), null=True, verbose_name='Aktsiya yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stock/', verbose_name='Aksiya eloni rasmi'),
        ),
    ]
