# Generated by Django 5.1.1 on 2024-10-17 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('naqt', 'Naqt'), ('terminal', 'Terminal'), ('click', 'Click')], max_length=221, null=True, verbose_name="To'lov shakli"),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 17, 14, 46, 57, 980200), null=True, verbose_name='Buyurtma berilgan vaqt'),
        ),
    ]
