# Generated by Django 5.1.1 on 2024-10-17 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_order_payment_alter_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='description',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='stock',
            name='products_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Aksiya linki'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 17, 16, 11, 47, 791028), null=True, verbose_name='Buyurtma berilgan vaqt'),
        ),
    ]
