# Generated by Django 5.1.1 on 2024-10-17 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_remove_stock_description_remove_stock_image_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 17, 16, 39, 23, 966670), null=True, verbose_name='Buyurtma berilgan vaqt'),
        ),
    ]
